# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/mitsutaka/zcmd
    steps:
      - checkout
      - run:
          name: Setup tools
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
      - run: go get -v -t -d ./...
      - run: golangci-lint run --enable-all -v ./...
      - run: go test -v ./...